### ISSUE TITLE
Error on index

### ISSUE THREAD

**Issue by RasonJ** [o19s/chorus-opensearch-edition#17]
When indexing, many docs yield the following errors:
```
2024-02-22 09:59:51 [2024-02-22T17:59:51,367][INFO ][o.o.a.b.TransportShardBulkAction] [opensearch] [ecommerce][0] mapping update rejected by primary
2024-02-22 09:59:51 java.lang.IllegalArgumentException: Limit of total fields [1000] has been exceeded
2024-02-22 09:59:51     at org.opensearch.index.mapper.MappingLookup.checkFieldLimit(MappingLookup.java:193) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 09:59:51     at org.opensearch.index.mapper.MappingLookup.checkLimits(MappingLookup.java:185) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 09:59:51     at org.opensearch.index.mapper.DocumentMapper.validate(DocumentMapper.java:329) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 09:59:51     at org.opensearch.index.mapper.MapperService.internalMerge(MapperService.java:488) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 09:59:51     at org.opensearch.index.mapper.MapperService.internalMerge(MapperService.java:444) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 09:59:51     at org.opensearch.index.mapper.MapperService.merge(MapperService.java:416) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 09:59:51     at org.opensearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:633) [opensearch-2.11.1.jar:2.11.1]
2024-02-22 09:59:51     at org.opensearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:466) [opensearch-2.11.1.jar:2.11.1]
2024-02-22 09:59:51     at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) [opensearch-2.11.1.jar:2.11.1]
2024-02-22 09:59:51     at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.11.1.jar:2.11.1]
2024-02-22 09:59:51     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
2024-02-22 09:59:51     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
2024-02-22 09:59:51     at java.lang.Thread.run(Thread.java:833) [?:?]
```
and 
```
2024-02-22 10:02:33 Caused by: java.lang.IllegalArgumentException: Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [supplier] in order to load field data by uninverting the inverted index. Note that this can use significant memory.
2024-02-22 10:02:33     at org.opensearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:956) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:145) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.index.query.QueryShardContext.getForField(QueryShardContext.java:307) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.search.aggregations.support.ValuesSourceConfig.internalResolve(ValuesSourceConfig.java:173) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.search.aggregations.support.ValuesSourceConfig.resolve(ValuesSourceConfig.java:83) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.search.aggregations.support.ValuesSourceAggregationBuilder.resolveConfig(ValuesSourceAggregationBuilder.java:437) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:412) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:63) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:155) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:459) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.search.SearchService.parseSource(SearchService.java:1281) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.search.SearchService.createContext(SearchService.java:985) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:593) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:566) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:74) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:89) ~[opensearch-2.11.1.jar:2.11.1]
2024-02-22 10:02:33     at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.11.1.jar:2.11.1]
```

**Comment by RasonJ** [comment]
@jzonthemtn already fixed this.
